### ISSUE TITLE
Error downloading PDF file with wkhtmlpdf from repo

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#23]
When trying to download the PDF file the system outputs the error:
```
RuntimeError (Failed to execute:
                                                                      ["/usr/bin/wkhtmltopdf", "-q", "--margin-top", "25", "--margin-bottom", "20", "--margin-left", "12", "--margin-right", "12", "--footer-center", "Created using DMPRoadmap. Last modified 27 August 2020", "--footer-right", "[page] of [topage]", "--footer-font-size", "8", "--footer-spacing", "6", "file:////tmp/wicked_pdf20200827-24807-1nks7m3.html", "/tmp/wicked_pdf_generated_file20200827-24807-hij1j7.pdf"]
                                                                      Error: PDF could not be generated!
                                                                       Command Error: The switch --footer-center, is not support using unpatched qt, and will be ignored.The switch --footer-right, is not support using unpatched qt, and will be ignored.The switch --footer-font-size, is not support using unpatched qt, and will be ignored.The switch --footer-spacing, is not support using unpatched qt, and will be ignored.wkhtmltopdf: cannot connect to X server 
                                                                      ):
                                                                        app/controllers/plan_exports_controller.rb:76:in `show_pdf'
                                                                        app/controllers/plan_exports_controller.rb:44:in `block (2 levels) in show'
                                                                        app/controllers/plan_exports_controller.rb:39:in `show'

```

**Comment by lagoan** [comment]
Added support with patched QT libraries
