### ISSUE TITLE
Missing asset _tinymce_content.css

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#25]
**Expected behaviour:**
When I use the web application normally, it shouldn't generate any error messages.

**Actual behaviour:**
While clicking around in Production, and monitoring the log files, I saw /var/log/httpd/error_log getting this message:
```
==> error_log <==
App 54221 output: ActionController::RoutingError (No route matches [GET] "/assets/blocks/_tinymce_content.css"):
App 54221 output:   vendor/ruby/2.5.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/rollbar-2.26.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
App 54221 output:   vendor/ruby/2.5.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:38:in `call_app'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `block in call'
App 54221 output:   vendor/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 54221 output:   vendor/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:26:in `tagged'
App 54221 output:   vendor/ruby/2.5.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `tagged'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/rack-1.6.13/lib/rack/methodoverride.rb:22:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/dragonfly-1.2.0/lib/dragonfly/cookie_monster.rb:9:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/rack-1.6.13/lib/rack/runtime.rb:18:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/static.rb:120:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/rack-1.6.13/lib/rack/sendfile.rb:113:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/engine.rb:518:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/application.rb:165:in `call'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `public_send'
App 54221 output:   vendor/ruby/2.5.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `method_missing'
App 54221 output:   /usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 54221 output:   /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 54221 output:   /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 54221 output:   /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 54221 output:   /usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```
**Steps to reproduce:**
I believe I simply clicked on :
![image](https://user-images.githubusercontent.com/3227828/97457794-b4901280-18ff-11eb-9f52-6c00975e0878.png)

Specifically, here's the line describing what I clicked on: 
```
==> access_log <==
129.128.216.11 - - [28/Oct/2020:09:18:21 -0600] "GET /assets/blocks/_tinymce_content.css HTTP/1.1" 404 435 "https://dmp-assistant.library.ualberta.ca/plans/4141/edit?phase_id=2076" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
```

I also tried this in the **Staging** environment, on southampton.  Here, logging is slightly different.  In 'access_log' I see that my browser's trying to load that .css file, and it's failing (404): 
`129.128.217.81 - - [28/Oct/2020:09:28:19 -0600] "GET /assets/blocks/_tinymce_content.css HTTP/1.1" 404 435 "https://dmptest.library.ualberta.ca/plans/4180/edit?phase_id=2085" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"`
... and the same "No route matches" error message falls over into syslog ("journalctl -f")

**Comment by lagoan** [comment]
Fixed in last tagged release 2.1.3+portage-0.0.31
