### ISSUE TITLE
ActiveRecord::StaleObjectError When Answer.lock_version == NULL in DB

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#525]
Relates to the following issues:
- https://github.com/portagenetwork/roadmap/issues/333
- https://github.com/DMPRoadmap/roadmap/issues/2520

`db>schema.rb` includes the following:
```ruby
  create_table "answers", id: :integer, force: :cascade do |t|
    t.text "text", limit: 16777215
    t.integer "plan_id"
    t.integer "user_id"
    t.integer "question_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer "lock_version", default: 0
    t.index ["plan_id"], name: "index_answers_on_plan_id"
    t.index ["question_id"], name: "index_answers_on_question_id"
    t.index ["user_id"], name: "fk_rails_584be190c2"
  end
```
However, this doesn't prevent null values in the db:

```ruby
2.7.6 :001 > Answer.where(lock_version: nil).count
   (14.1ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."lock_version" IS NULL
 => 47566 
```

## db lock_version = NULL
![Screenshot from 2023-11-07 13-08-42](https://github.com/portagenetwork/roadmap/assets/71047780/1412bd9d-529d-4fe9-ade5-c27b2bc11130)

##  lock_version for same answer is 0 in rails c
```ruby
$ rails c
Loading development environment (Rails 5.2.8.1)
irb: warn: can't alias context from irb_context.
2.7.6 :001 > Answer.find(47378).lock_version
  Answer Load (0.9ms)  SELECT  "answers".* FROM "answers" WHERE "answers"."id" = $1 LIMIT $2  [["id", 47378], ["LIMIT", 1]]
 => 0 
2.7.6 :002 > 
```

It appears that the StaleObjectError is occuring because rails reads lock_version as 0 (the default_value) when it is actually NULL in the db. I'm guessing the db is attempting to increment the lock_version to 0, but there is some conflict with the 0 coming from rails.

After reading online, it seems that this should be resolved by replacing all NULL values with 0 for lock_version:
https://stackoverflow.com/questions/28729163/rails-optimistic-locking-always-fires-staleobjecterror-exception
https://stackoverflow.com/questions/29358347/activerecordstaleobjecterror-on-object-with-has-one-association-and-accepts-ne

**Comment by aaronskiba** [comment]
Returns the default value (0) when the db value is NULL:
```ruby
$ rails c
Loading development environment (Rails 5.2.8.1)
irb: warn: can't alias context from irb_context.
2.7.6 :001 > Answer.where(lock_version: nil).first.lock_version
  Answer Load (1.7ms)  SELECT  "answers".* FROM "answers" WHERE "answers"."lock_version" IS NULL ORDER BY "answers"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => 0 
2.7.6 :002 > 
```

**Comment by aaronskiba** [comment]
![Screenshot from 2023-11-07 15-03-18](https://github.com/portagenetwork/roadmap/assets/71047780/b141c212-22c5-4ed5-bf7f-6db90225ddc2)
## WITH RESCUE BLOCK
![Screenshot from 2023-11-07 14-59-09](https://github.com/portagenetwork/roadmap/assets/71047780/24f9f9ab-2363-4481-8320-bc0552fb9576)

## WITHOUT RESCUE BLOCK
![Screenshot from 2023-11-07 13-34-25](https://github.com/portagenetwork/roadmap/assets/71047780/2b0f6cf1-c4d4-4103-bbe3-2bb32569bd99)
![Screenshot from 2023-11-07 14-57-40](https://github.com/portagenetwork/roadmap/assets/71047780/f88973f6-a03c-4bf2-aaa9-32d7d43831f6)
```ruby
Started POST "/answers/create_or_update?question_id=68125" for 127.0.0.1 at 2023-11-07 14:55:12 -0700
Processing by AnswersController#create_or_update as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"X8Qg2gPyXYh9X5VBEgVF/k6useqoyABMiMKyOvwZSWsXAkqN9m6eO1wLj37Z9Rnl8B5gLoSU3mCJsEhpsKX/bQ==", "answer"=>{"plan_id"=>"10486", "question_id"=>"68125", "lock_version"=>"0", "text"=>"<p>Testing 123</p>"}, "question_id"=>"68125"}
  Plan Load (1.7ms)  SELECT  "plans".* FROM "plans" WHERE "plans"."id" = $1 LIMIT $2  [["id", 10486], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:23
  Plan Exists (3.1ms)  SELECT  1 AS one FROM "plans" INNER JOIN "templates" ON "templates"."id" = "plans"."template_id" INNER JOIN "phases" ON "phases"."template_id" = "templates"."id" INNER JOIN "sections" ON "sections"."phase_id" = "phases"."id" INNER JOIN "questions" ON "questions"."section_id" = "sections"."id" WHERE "plans"."id" = $1 AND "questions"."id" = $2 LIMIT $3  [["id", 10486], ["id", 68125], ["LIMIT", 1]]
  ↳ app/models/plan.rb:548
  Question Load (0.9ms)  SELECT  "questions".* FROM "questions" WHERE "questions"."id" = $1 ORDER BY "questions"."number" ASC LIMIT $2  [["id", 68125], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:40
   (0.5ms)  BEGIN
  ↳ app/controllers/answers_controller.rb:43
  Answer Load (0.6ms)  SELECT  "answers".* FROM "answers" WHERE "answers"."plan_id" = $1 AND "answers"."question_id" = $2 LIMIT $3  [["plan_id", 10486], ["question_id", 68125], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:49
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 23389], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:53
  Plan Load (0.8ms)  SELECT  "plans".* FROM "plans" WHERE "plans"."id" = $1 LIMIT $2  [["id", 10486], ["LIMIT", 1]]
  ↳ app/policies/answer_policy.rb:11
  Role Load (0.7ms)  SELECT "roles".* FROM "roles" WHERE "roles"."plan_id" = $1  [["plan_id", 10486]]
  ↳ app/models/plan.rb:377
  QuestionOption Load (0.9ms)  SELECT "question_options".* FROM "question_options" WHERE 1=0
  ↳ app/controllers/answers_controller.rb:55
  QuestionOption Load (0.9ms)  SELECT "question_options".* FROM "question_options" INNER JOIN "answers_question_options" ON "question_options"."id" = "answers_question_options"."question_option_id" WHERE "answers_question_options"."answer_id" = $1  [["answer_id", 47378]]
  ↳ app/controllers/answers_controller.rb:55
  Question Load (0.6ms)  SELECT  "questions".* FROM "questions" WHERE "questions"."id" = $1 ORDER BY "questions"."number" ASC LIMIT $2  [["id", 68125], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:55
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 23389], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:55
  Answer Exists (0.8ms)  SELECT  1 AS one FROM "answers" WHERE "answers"."question_id" = $1 AND "answers"."id" != $2 AND "answers"."plan_id" = $3 LIMIT $4  [["question_id", 68125], ["id", 47378], ["plan_id", 10486], ["LIMIT", 1]]
  ↳ app/controllers/answers_controller.rb:55
  Answer Update (0.7ms)  UPDATE "answers" SET "text" = $1, "updated_at" = $2, "lock_version" = $3 WHERE "answers"."id" = $4 AND "answers"."lock_version" = $5  [["text", "<p>Testing 123</p>"], ["updated_at", "2023-11-07 21:55:13.034654"], ["lock_version", 1], ["id", 47378], ["lock_version", 0]]
  ↳ app/controllers/answers_controller.rb:55
   (1.0ms)  ROLLBACK
  ↳ app/controllers/answers_controller.rb:43
Completed 409 Conflict in 40ms (ActiveRecord: 17.3ms)



ActiveRecord::StaleObjectError - Attempted to update a stale object: Answer.:
  app/controllers/answers_controller.rb:55:in `block in create_or_update'
  app/controllers/answers_controller.rb:43:in `create_or_update'
```

**Comment by aaronskiba** [comment]
- https://github.com/rails/rails/issues/36264

**Comment by aaronskiba** [comment]
**The upgrade to Rails 6 appears to solve this issue :)**

![Screenshot from 2024-01-08 12-27-52](https://github.com/portagenetwork/roadmap/assets/71047780/de4316c9-6cf3-4403-8591-284c58832849)
```
aaron@ubuntu:~/Documents/GitHub/roadmap
$ rails s
=> Booting Puma
=> Rails 5.2.8.1 application starting in development 
```
![Screenshot from 2024-01-08 12-29-39](https://github.com/portagenetwork/roadmap/assets/71047780/2607fd89-ddb8-4fcc-9f8b-dac98a006b18)

```
aaron@ubuntu:~/Documents/GitHub/roadmap
$ rails s
=> Booting Puma
=> Rails 6.1.7.6 application starting in development
```

![Screenshot from 2024-01-08 12-31-33](https://github.com/portagenetwork/roadmap/assets/71047780/596322b4-9e18-4b98-8ea0-1bb11afa3fb5)
