### ISSUE TITLE
RuntimeError Due to Spring Trying to Reload in Production Mode

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#541]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- This currently exists on the branch where we are merging DMPRoadmap releases v4.0.0, v4.0.1, and v4.0.2

The spring gem is only to be used in development, and the Gemfile correctly limits its usage to only that environment.

However, the command `RAILS_ENV=production rails c` results in the following error:

```ruby
aaron@ubuntu:~/Documents/GitHub/roadmap
$ RAILS_ENV=production rails c
/usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:100:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/production.rb.
 (RuntimeError)
        from /usr/share/rvm/gems/ruby-2.7.6/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `each'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `call'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
        from /home/aaron/Documents/GitHub/roadmap/config/environment.rb:7:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:107:in `preload'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:166:in `serve'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:148:in `block in run'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:142:in `loop'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application.rb:142:in `run'
        from /usr/share/rvm/gems/ruby-2.7.6/gems/spring-4.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from -e:1:in `<main>'
aaron@ubuntu:~/Documents/GitHub/roadmap
```

**Comment by aaronskiba** [comment]
[Roadmap Release v4.1.1](https://github.com/DMPRoadmap/roadmap/releases/tag/v4.1.1) appears to address this problem. The release notes state the following:
- Solved issue where spring was loaded in production mode : ran `bin/spring binstub --all`

Applying `bin/spring binstub --all` to our codebase results in the following:
```ruby
aaron@ubuntu:~/Documents/GitHub/roadmap
$ RAILS_ENV=production rails c
Loading production environment (Rails 6.1.7.6)
2.7.6 :001 > 
```
