### ISSUE TITLE
Flagshihtzu.check_for_column Warnings/Error On Docker-UAT Workflow

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#542]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- This currently exists on the branch where we are merging DMPRoadmap releases v4.0.0, v4.0.1, and v4.0.2

Flagshihtzu.check_for_column is true by default. The incoming changes from DMPRoadmap releases v4.0.0, v4.0.1, and v4.0.2 set `check_for_column: !Rails.env.test?` for all of these column checks.

The Docker-UAT workflow uses `RAILS_ENV=production`. The `Build and push Docker image` step of this workflow is failing ([example](https://github.com/aaronskiba/roadmap/actions/runs/6985453434/job/19076200423#step:5:1049)). Here is a snippet of the output:

```
#20 25.11 FlagShihTzu#has_flags: Table "identifier_schemes" doesn't exist.  Have all migrations been run?
#20 25.11 FlagShihTzu says: Flag column context appears to be missing!
#20 25.11 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/identifier_scheme.rb:49:in `<class:IdentifierScheme>'
#20 25.11 FlagShihTzu#has_flags: Table "identifier_schemes" doesn't exist.  Have all migrations been run?
#20 25.11 FlagShihTzu says: Flag column context appears to be missing!
#20 25.11 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/identifier_scheme.rb:49:in `<class:IdentifierScheme>'
#20 25.11 /bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `for_authentication' for IdentifierScheme(Table doesn't exist):Class (NoMethodError)
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:9:in `<class:OmniauthCallbacksController>'
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:8:in `<module:Users>'
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:3:in `<top (required)>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `cget'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `eager_load_all'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
#20 25.11 	from /usr/src/app/config/environment.rb:7:in `<top (required)>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/actions.rb:28:in `require_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:33:in `perform'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<top (required)>'
#20 25.11 	from bin/rails:10:in `require'
#20 25.11 	from bin/rails:10:in `<main>'
#20 25.11 /bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `for_authentication' for IdentifierScheme(Table doesn't exist):Class (NoMethodError)
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:9:in `<class:OmniauthCallbacksController>'
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:8:in `<module:Users>'
#20 25.11 	from /usr/src/app/app/controllers/users/omniauth_callbacks_controller.rb:3:in `<top (required)>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `cget'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `eager_load_all'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
#20 25.11 	from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
#20 25.11 	from /usr/src/app/config/environment.rb:7:in `<top (required)>'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
#20 25.11 	from /bundle/ruby/2.7.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/actions.rb:28:in `require_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:33:in `perform'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
#20 25.11 	from /bundle/ruby/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
#20 25.11 	from /bundle/ruby/2.7.0/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<top (required)>'
#20 25.11 	from bin/rails:10:in `require'
#20 25.11 	from bin/rails:10:in `<main>'
#20 25.11 
#20 ERROR: process "/bin/sh -c DATABASE_URL=***127.0.0.1/roadmap RAILS_ENV=production SECRET_KEY_BASE=change_me DEVISE_SECRET_KEY=pickasecuretoken bundle exec rake assets:precompile" did not complete successfully: exit code: 1
```

**Comment by aaronskiba** [comment]
Setting `check_for_column: false` within IdentifierScheme enables the workflow to pass([example](https://github.com/aaronskiba/roadmap/actions/runs/6985536071)). However, the check_for_column warnings still appear for the remaining columns (output below):

```
#20 61.08 Compiled all packs in /usr/src/app/public/packs
#20 61.08 Browserslist: caniuse-lite is outdated. Please run:
#20 61.08   npx update-browserslist-db@latest
#20 61.08   Why you should do it regularly: https://github.com/browserslist/update-db#readme
#20 61.08 FlagShihTzu#has_flags: Table "contributors" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column roles appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/contributor.rb:67:in `<class:Contributor>'
#20 61.08 FlagShihTzu#has_flags: Table "orgs" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column org_type appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/org.rb:175:in `<class:Org>'
#20 61.08 FlagShihTzu#has_flags: Table "roles" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column access appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/role.rb:43:in `<class:Role>'
#20 61.08 FlagShihTzu#has_flags: Table "contributors" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column roles appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/contributor.rb:67:in `<class:Contributor>'
#20 61.08 FlagShihTzu#has_flags: Table "contributors" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column roles appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/contributor.rb:67:in `<class:Contributor>'
#20 61.08 FlagShihTzu#has_flags: Table "orgs" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column org_type appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/org.rb:175:in `<class:Org>'
#20 61.08 FlagShihTzu#has_flags: Table "orgs" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column org_type appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/org.rb:175:in `<class:Org>'
#20 61.08 FlagShihTzu#has_flags: Table "roles" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column access appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/role.rb:43:in `<class:Role>'
#20 61.08 FlagShihTzu#has_flags: Table "roles" doesn't exist.  Have all migrations been run?
#20 61.08 FlagShihTzu says: Flag column access appears to be missing!
#20 61.08 To turn off this warning set check_for_column: false in has_flags definition here: /usr/src/app/app/models/role.rb:43:in `<class:Role>'
#20 61.08 
#20 DONE 61.3s
```

**Comment by aaronskiba** [comment]
Perhaps creating a secret/ENV variable for the check_for_column boolean values is the best way to address this issue?

**Comment by aaronskiba** [comment]
```
#20 25.11 /bundle/ruby/2.7.0/gems/activerecord-6.1.7.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing':
undefined method `for_authentication' for IdentifierScheme(Table doesn't exist):Class (NoMethodError)
```

The following code in `app/controllers/users/omniauth_callbacks_controller.rb` is causing the NoMethodError:
```ruby
    # Dynamically build a handler for each omniauth provider
    # -------------------------------------------------------------
    IdentifierScheme.for_authentication.each do |scheme|
      define_method(scheme.name.downcase) do
        handle_omniauth(scheme)
      end
    end

```

**Comment by aaronskiba** [comment]
I can see that a previous commit was made to address this same issue with the IdentifierScheme table:
https://github.com/portagenetwork/roadmap/commit/52a09c20bb134fa7c2827a76bc94fae7eadb01eb#diff-b1d995b28b3ca4cb4269692ed5a8a6368fd272b6575666888d9d83c1645394a9L54

Here, the issue was addressed by simply setting `check_for_column` to false. Rather, than creating another secret, maybe setting this column to false is the best way to handle things?
