### ISSUE TITLE
Duplicate Entries In Answers Table

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#593]
Please complete the following fields as applicable:
- Existing upstream issue: https://github.com/DMPRoadmap/roadmap/issues/3362

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- Encountered both in release 3.3.1+portage-3.2.2 and upcoming v4.0.2 upgrade

**Expected behaviour:**
- User should be able to copy an existing plan.

**Actual behaviour:**
- Due to the duplicate answers in the db, the following is encountered when attempting to copy a plan:
![Screenshot from 2024-01-08 11-37-20](https://github.com/portagenetwork/roadmap/assets/71047780/6145a0f2-23b8-4855-9574-cefb111c7099)

```
Answer Exists? (3.2ms)  SELECT 1 AS one FROM "answers" WHERE "answers"."question_id" = $1 AND "answers"."plan_id" = $2 LIMIT $3  [["question_id", 69714], ["plan_id", 11709], ["LIMIT", 1]]
  ↳ app/models/plan.rb:258:in `block in deep_copy'
  TRANSACTION (2.1ms)  ROLLBACK
  ↳ app/models/plan.rb:258:in `block in deep_copy'
Completed 422 Unprocessable Entity in 1265ms (ActiveRecord: 172.8ms | Allocations: 1031012)



ActiveRecord::RecordInvalid - Validation failed: Question must be unique:
  app/models/plan.rb:258:in `block in deep_copy'
  app/models/plan.rb:255:in `deep_copy'
```

**Comment by aaronskiba** [comment]
**QUERYING FOR DUPLICATE ANSWERS**

```SQL
SELECT text, plan_id, user_id, question_id, created_at, updated_at, lock_version
FROM public.answers
GROUP BY text, plan_id, user_id, question_id, created_at, updated_at, lock_version
HAVING COUNT(*) > 1;
```

| "text" | "plan_id" | "user_id" | "question_id" | "created_at" | "updated_at" | "lock_version" |
|---|---|---|---|---|---|---|
| "<p>N/A</p>" | 9347 | 22438 | 69723 | "2022-06-04 04:46:48" | "2022-06-04 04:46:48" | NULL |
| "<p>Purpose of study</p><p>Research question and hypotheses&nbsp;</p><p>Measurements of key variables</p><p>Data collection procedure&nbsp;</p><p>Variable definitions and value descriptions (coding book including IV  DV  and MEDs)</p><p>Data analyses and results (syntax files)</p><p>&nbsp;</p>" | 9347 | 22438 | 69714 | "2022-06-04 02:52:42" | "2022-06-04 02:52:42" | NULL |
| "<p>The data would need to be de-identified to the extent of protecting trade-secrets</p>" | 8424 | 20974 | 68834 | "2021-12-17 23:01:46" | "2021-12-17 23:01:46" | NULL |
| "<p>This project is not currently being funded and therefore I utilize the free and open-source resources available for implementing my data management plan.</p>" | 6914 | 20533 | 67418 | "2021-04-02 19:54:36" | "2021-04-02 19:54:36" | NULL |

**Comment by aaronskiba** [comment]
Closing this issue as it is a symptom that will be remedied after addressing issue https://github.com/portagenetwork/roadmap/issues/800.
