### ISSUE TITLE
500 Error When Downloading JSON Plan

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#609]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- Upcoming v4 Release

**Expected behaviour:**
- User should be able to successfully 'download' a JSON version of a plan.
**Actual behaviour:**
- `{"status":500,"error":"Internal Server Error"}` is returned instead.

Here is the syslog entry pertaining to this error:
```ruby
17 11:13:08 ubuntu dmp_assistant[965002]: ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
#012    23: json.ethical_issues_description plan.ethical_issues_description
#012    24: json.ethical_issues_report plan.ethical_issues_report
#012    25: 
#012    26: id = presenter.identifier
#012    27: if id.present?
#012    28:   json.dmp_id do
#012    29:     json.partial! 'api/v1/identifiers/show', identifier: id
#012  #012app/presenters/api/v1/plan_presenter.rb:35:in `identifier'
#012app/views/api/v1/plans/_show.json.jbuilder:26
#012app/controllers/plan_exports_controller.rb:117:in `show_json'
#012app/controllers/plan_exports_controller.rb:65:in `block (2 levels) in show'
#012app/controllers/plan_exports_controller.rb:59:in `show'

```

**Comment by aaronskiba** [comment]
This had to do with the `DMPROADMAP_HOST` variable not being included in the .env file. The issue didn't exist on my local environment, but it did on UAT.
