### ISSUE TITLE
Rack-Attack Blocking & Throttling Requests From Features Tests

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#627]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- Upstream Release `v4.1.0`

**Observations:**
- Executing `rspec ./spec/features/plans/exports_spec.rb` results in multiple tests failing with output similar to the following:

```ruby
  1) PlansExports User downloads org plan belonging to User in same org
     Failure/Error:
       within("#plan_#{plan.id}") do
         click_button('Actions')
         click_link 'Download'
       end
     
     Capybara::ElementNotFound:
       Unable to find css "#plan_1"
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/node/finders.rb:312:in `block in synced_resolve'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/node/base.rb:84:in `synchronize'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/node/finders.rb:301:in `synced_resolve'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/node/finders.rb:60:in `find'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/session.rb:773:in `find'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/session.rb:362:in `within'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `call'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `within_element'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/capybara-3.39.2/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/features/plans/exports_spec.rb:56:in `block (2 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.0.5@dmp/gems/webmock-3.19.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```
- To help diagnose the tests, the following code was temporarily added to the tests:
![Screenshot from 2024-01-26 15-19-13](https://github.com/portagenetwork/roadmap/assets/71047780/26bbc766-5add-4697-8d6d-3662a9719941)
- The following screenshot corresponds with a failed test:
![capybara-202401261522483577485964](https://github.com/portagenetwork/roadmap/assets/71047780/2073e070-775b-4278-8e02-7ee2d5986810)
- After setting `Rack::Attack.enabled = false`, in `config/initializers/rack_attack.rb`, all of the tests pass after executing `rspec ./spec/features/plans/exports_spec.rb`.

**Comment by aaronskiba** [comment]
A fix now exists within PR #700 (soon to be merged).
