### ISSUE TITLE
Improve Load Time of "Edit Profile" Page

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#880]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.1.1+portage-4.1.3`

**Expected behaviour:**
- Users will be navigating to this page to link their app account via SSO. We should expect frequent usage and have it load as fast as possible.

**Actual behaviour:**
- The page currently feels slow to load. The causes will have to be investigated, but N+1 query warnings currently appear to be part of the problem (see below):

```
Completed 200 OK in 2565ms (Views: 1907.5ms | ActiveRecord: 601.3ms | Allocations: 419232)


user: aaron
GET /users/edit
USE eager loading detected
  Org => [:identifiers]
  Add to your query: .includes([:identifiers])
Call stack
  /home/aaron/Documents/GitHub/roadmap/app/services/org_selection/org_to_hash_service.rb:29:in `to_hash'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:17:in `block in initialize'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:14:in `map'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:14:in `initialize'
  /home/aaron/Documents/GitHub/roadmap/app/views/shared/org_selectors/_local_only.html.erb:11:in `new'
  /home/aaron/Documents/GitHub/roadmap/app/views/shared/org_selectors/_local_only.html.erb:11:in `_app_views_shared_org_selectors__local_only_html_erb___2970257573569036849_43440'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/_personal_details.html.erb:27:in `block in _app_views_devise_registrations__personal_details_html_erb__1502139585486093410_63620'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/_personal_details.html.erb:1:in `_app_views_devise_registrations__personal_details_html_erb__1502139585486093410_63620'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/edit.html.erb:35:in `_app_views_devise_registrations_edit_html_erb__420084449021199597_63500'


user: aaron
GET /users/edit
USE eager loading detected
  Identifier => [:identifier_scheme]
  Add to your query: .includes([:identifier_scheme])
Call stack
  /home/aaron/Documents/GitHub/roadmap/app/services/org_selection/org_to_hash_service.rb:30:in `block in to_hash'
  /home/aaron/Documents/GitHub/roadmap/app/services/org_selection/org_to_hash_service.rb:29:in `to_hash'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:17:in `block in initialize'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:14:in `map'
  /home/aaron/Documents/GitHub/roadmap/app/presenters/org_selection_presenter.rb:14:in `initialize'
  /home/aaron/Documents/GitHub/roadmap/app/views/shared/org_selectors/_local_only.html.erb:11:in `new'
  /home/aaron/Documents/GitHub/roadmap/app/views/shared/org_selectors/_local_only.html.erb:11:in `_app_views_shared_org_selectors__local_only_html_erb___2970257573569036849_43440'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/_personal_details.html.erb:27:in `block in _app_views_devise_registrations__personal_details_html_erb__1502139585486093410_63620'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/_personal_details.html.erb:1:in `_app_views_devise_registrations__personal_details_html_erb__1502139585486093410_63620'
  /home/aaron/Documents/GitHub/roadmap/app/views/devise/registrations/edit.html.erb:35:in `_app_views_devise_registrations_edit_html_erb__420084449021199597_63500'
```

**Comment by aaronskiba** [comment]
Improvements have been made here and the page load is now ~42% faster.
Further improvements can probably be made by addressing the following line in `app/views/shared/org_selectors/_local_only.html.erb`:
```ruby
presenter = OrgSelectionPresenter.new(orgs: orgs.select{|org| org.managed == true}, selection: default_org)
```
Improvements could be made by performing this `org.managed == true` filter at the db level. However, several controllers are using this view, so it will have to be handled carefully. I am closing this current issue and will deal with the further potential improvements in a new issue.
