### ISSUE TITLE
Unable to Execute `bundle exec rake translation:sync` When `config.disable_yaml = false`

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#920]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
`4.1.1+portage-4.2.2`

**Expected behaviour:**

**Actual behaviour:**
After setting   `config.disable_yaml = false` within `config/initializers/translation.rb`:
```
$ bundle exec rake translation:sync --trace
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
** Invoke translation:sync (first_time)
** Invoke environment (first_time)
** Execute environment
Copying Bootstrap glyphicons to the public directory ...
Copying TinyMCE skins to the public directory ...
** Execute translation:sync
* Downloading YAML source editions.
* Applying YAML source editions.
rake aborted!
Psych::BadAlias: Unknown alias: new
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych.rb:334:in `safe_load'
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych.rb:369:in `load'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:49:in `block in reload_or_reuse_yaml_sources'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:47:in `collect'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:47:in `reload_or_reuse_yaml_sources'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:22:in `block in run'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:19:in `each'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation/apply_yaml_source_edits_step.rb:19:in `run'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client/sync_operation.rb:27:in `run'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/client.rb:19:in `sync'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bundler/gems/translation_io_rails-6fbb2cd619e7/lib/translation_io/tasks.rb:23:in `block (2 levels) in <top (required)>'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
/usr/share/rvm/gems/ruby-3.1.4@dmp/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bin/rake:25:in `load'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bin/rake:25:in `<main>'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bin/ruby_executable_hooks:22:in `eval'
/usr/share/rvm/gems/ruby-3.1.4@dmp/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => translation:sync

```

**Comment by aaronskiba** [comment]
The root cause of this issue is outlined here: 
- https://github.com/portagenetwork/roadmap/issues/933

I have tagged this issue within issue #933. Also, I am closing this issue because it will be resolved after #933 is resolved.
